# Generated by Django 4.2.6 on 2023-10-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Situational Report', 'Situational Report'), ('Incident Report', 'Incident Report'), ('Flood Report', 'Flood Report'), ('Earthquake Report', 'Earthquake Report'), ('Landslide Report', 'Landslide Report'), ('Weather Report', 'Weather Report')], max_length=50)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='report_attachments/')),
                ('respondent_name', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_reported', models.DateField()),
                ('time_reported', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('barangay', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('mdrrmc', 'MDRRMC Admin'), ('barangay', 'Barangay Admin')], default='mdrrmc', max_length=8)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
