# Generated by Django 4.2.6 on 2023-11-01 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0004_alter_announcement_barangay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='barangay',
        ),
        migrations.AddField(
            model_name='announcement',
            name='barangay',
            field=models.ManyToManyField(related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
