# Generated by Django 4.2.6 on 2023-11-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0005_remove_announcement_barangay_announcement_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
