# Generated by Django 4.2.6 on 2023-11-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0006_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(choices=[('Situational Report', 'Situational Report'), ('Incident Report', 'Incident Report'), ('Flood Report', 'Flood Report'), ('Earthquake Report', 'Earthquake Report'), ('Landslide Report', 'Landslide Report'), ('Weather Report', 'Weather Report'), ('Typhoon Report', 'Typhoon Report')], max_length=50),
        ),
    ]
