# Generated by Django 4.2.6 on 2023-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0008_adminreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNaturalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Flood Report', 'Flood Report'), ('Earthquake Report', 'Earthquake Report'), ('Landslide Report', 'Landslide Report'), ('Weather Report', 'Weather Report'), ('Typhoon Report', 'Typhoon Report')], max_length=50)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='report_attachments/')),
                ('respondent_name', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_reported', models.DateField()),
                ('time_reported', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
