# Generated by Django 4.2.6 on 2023-11-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0009_adminnaturalreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnaturalreport',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='adminnaturalreport',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='adminnaturalreport',
            name='respondent_name',
        ),
    ]
