# Generated by Django 4.2.6 on 2023-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0010_remove_adminnaturalreport_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(choices=[('Situational Report', 'Situational Report'), ('Incident Report', 'Incident Report')], max_length=50),
        ),
    ]
