# Generated by Django 4.2.6 on 2023-11-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0018_alter_report_time_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_reported',
            field=models.TimeField(),
        ),
    ]
