# Generated by Django 4.2.6 on 2023-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0019_alter_report_time_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='report',
            name='respondent_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='time_reported',
        ),
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(choices=[('Situational Report', 'Situational Report'), ('Incident Report', 'Incident Report'), ('Flood Report', 'Flood Report'), ('Earthquake Report', 'Earthquake Report'), ('Landslide Report', 'Landslide Report'), ('Weather Report', 'Weather Report'), ('Typhoon Report', 'Typhoon Report')], max_length=50),
        ),
    ]
