# Generated by Django 5.0 on 2023-12-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0020_remove_report_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_reported',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
