# Generated by Django 5.0 on 2023-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0021_report_time_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='response_status',
            field=models.CharField(blank=True, choices=[('Responded', 'Responded'), ('Declined', 'Declined')], max_length=20, null=True),
        ),
    ]
