# Generated by Django 5.0 on 2023-12-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0022_report_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brgylatitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='brgylongitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
