# Generated by Django 5.0 on 2023-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0023_customuser_brgylatitude_customuser_brgylongitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
