# Generated by Django 5.0 on 2023-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0024_report_respondent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='reportedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
